[package]
name = "desen_web_rust_formulario"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "*"
rocket_contrib = { version = "0.4.8", features = ["json"] }
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0"

