[package]
name = "desen_requisicao_post_formulario_parte2"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5.1"
rocket_contrib = { version = "*", features = ["json"] }
serde = { version = "*", features = ["derive"] } 
serde_json = "*"
